
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 22 01:52:44 BRT 2011
//----------------------------------------------------

package compil.fortran;

/** CUP generated interface containing symbol constants. */
public interface FortranSym {
  /* terminals */
  public static final int AND = 11;
  public static final int LT = 5;
  public static final int NE = 8;
  public static final int MULTIPLY = 16;
  public static final int PLUS = 14;
  public static final int OR = 12;
  public static final int CALL = 20;
  public static final int GOTO = 18;
  public static final int NOT = 13;
  public static final int FUNCTION = 4;
  public static final int GT = 10;
  public static final int ID = 3;
  public static final int LE = 6;
  public static final int EOF = 0;
  public static final int DIVIDE = 17;
  public static final int ANY = 2;
  public static final int GE = 9;
  public static final int MINUS = 15;
  public static final int error = 1;
  public static final int EQ = 7;
  public static final int SUBROUTINE = 19;
}

