
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 28 01:49:40 BRT 2011
//----------------------------------------------------

package compil.fortran;

/** CUP generated interface containing symbol constants. */
public interface FortranSym {
  /* terminals */
  public static final int DIVIDE = 38;
  public static final int FUNCTION = 4;
  public static final int ANY = 2;
  public static final int GE = 30;
  public static final int CASE = 25;
  public static final int SUBROUTINE = 6;
  public static final int LPAREN = 39;
  public static final int CONTINUE = 11;
  public static final int ENDDO = 24;
  public static final int MINUS = 36;
  public static final int RPAREN = 40;
  public static final int NOT = 34;
  public static final int AND = 32;
  public static final int LT = 26;
  public static final int OR = 33;
  public static final int COMMA = 8;
  public static final int SEMICOL = 14;
  public static final int CALL = 7;
  public static final int SELECT = 23;
  public static final int MULTIPLY = 37;
  public static final int PLUS = 35;
  public static final int IF = 15;
  public static final int DOT = 13;
  public static final int ID = 3;
  public static final int LE = 27;
  public static final int EOF = 0;
  public static final int TRUE = 20;
  public static final int PROGRAM = 43;
  public static final int error = 1;
  public static final int EQ = 28;
  public static final int COLON = 9;
  public static final int ENDIF = 22;
  public static final int ELSE = 17;
  public static final int STOP = 12;
  public static final int GOTO = 5;
  public static final int WHILE = 19;
  public static final int DCOLON = 10;
  public static final int THEN = 16;
  public static final int label = 41;
  public static final int NE = 29;
  public static final int END = 42;
  public static final int FALSE = 21;
  public static final int GT = 31;
  public static final int DO = 18;
}

